# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_male', models.PositiveIntegerField(default=0)),
                ('total_female', models.PositiveIntegerField(default=0)),
                ('total_private', models.PositiveIntegerField(default=0)),
                ('total_local_jails', models.PositiveIntegerField(default=0)),
                ('total_other_prison', models.PositiveIntegerField(default=0)),
                ('total_non_citizen', models.PositiveIntegerField(default=0)),
                ('total_minor', models.PositiveIntegerField(default=0)),
                ('year', models.IntegerField(choices=[(2014, '2014'), (2015, '2015'), (2016, '2016')])),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'State Data',
            },
        ),
    ]
