# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_male', models.PositiveIntegerField(default=0)),
                ('total_female', models.PositiveIntegerField(default=0)),
                ('total_private', models.PositiveIntegerField(default=0)),
                ('total_local_jails', models.PositiveIntegerField(default=0)),
                ('total_other_prison', models.PositiveIntegerField(default=0, null=True)),
                ('total_non_citizen', models.PositiveIntegerField(default=0)),
                ('total_minor', models.PositiveIntegerField(default=0)),
                ('year', models.IntegerField(choices=[(2014, '2014'), (2015, '2015'), (2016, '2016')])),
                ('state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Conneticut', 'Conneticut'), ('Delaware', 'Delaware'), ('District of Colombia', 'District of Columbia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South_Carolina', 'South_Carolina'), ('South_Dakota', 'South_Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=100, null=True)),
                ('territory', models.CharField(choices=[('American Samoa', 'American Samoa'), ('Guam', 'Guam'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Puerto Rico', 'Puerto Rico'), ('Virgin Islands', 'Virgin Islands')], max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'State Data',
            },
        ),
    ]
