# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_male_supervised', models.PositiveIntegerField(blank=True, null=True)),
                ('total_female_supervised', models.PositiveIntegerField(blank=True, null=True)),
                ('total_male_incarcerated', models.PositiveIntegerField(blank=True, null=True)),
                ('total_female_incarcerated', models.PositiveIntegerField(blank=True, null=True)),
                ('total_private', models.PositiveIntegerField(blank=True, null=True)),
                ('total_local_jail', models.PositiveIntegerField(blank=True, null=True)),
                ('total_other_prison', models.PositiveIntegerField(blank=True, null=True)),
                ('total_noncitizen', models.PositiveIntegerField(blank=True, null=True)),
                ('total_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, choices=[(2014, '2014'), (2015, '2015'), (2016, '2016')], null=True)),
                ('state_or_territory', models.CharField(blank=True, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Conneticut', 'Conneticut'), ('Delaware', 'Delaware'), ('District of Colombia', 'District of Columbia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South_Carolina'), ('South Dakota', 'South_Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming'), ('Federal Total', 'Federal Total'), ('US Total', 'US Total'), ('Total for Prisons', 'Total for Prisons'), ('State Total', 'State Total'), ('American Samoa', 'American Samoa'), ('Guam', 'Guam'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Puerto Rico', 'Puerto Rico'), ('Virgin Islands', 'Virgin Islands')], max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('race_white', models.PositiveIntegerField(blank=True, null=True)),
                ('race_black', models.PositiveIntegerField(blank=True, null=True)),
                ('race_hispanic', models.PositiveIntegerField(blank=True, null=True)),
                ('race_american_indian_alaska_native', models.PositiveIntegerField(blank=True, null=True)),
                ('race_asian', models.PositiveIntegerField(blank=True, null=True)),
                ('race_native_hawaiian_pacific_islander', models.PositiveIntegerField(blank=True, null=True)),
                ('race_two_or_more', models.PositiveIntegerField(blank=True, null=True)),
                ('race_other', models.PositiveIntegerField(blank=True, null=True)),
                ('race_unknown', models.PositiveIntegerField(blank=True, null=True)),
                ('total_correction_pop', models.PositiveIntegerField(blank=True, null=True)),
                ('total_pop_incarcerated', models.PositiveIntegerField(blank=True, null=True)),
                ('total_correction_pop_per_one_hundred_thou_residents_all', models.PositiveIntegerField(blank=True, null=True)),
                ('total_pop_incarcerated_per_one_hundred_thou_residents_all', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'State Data',
            },
        ),
    ]
